name: Remove Label

on: pull_request

jobs:
  VRT:
    runs-on: salesforce-ux-emu-Ubuntu
    steps:
      - uses: actions/checkout@v3
      - uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: |
            vrt:chromatic
